name: "Publish"

on:
  workflow_dispatch:
    branches:
      - main
  release:
    types: [published]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Publish
        uses: home-assistant/builder@master
        env:
          CAS_API_KEY: ${{ secrets.CAS_API_KEY }}
        with:
          args: |
            --all \
            --target amcrest2mqtt-addon \
            --docker-user ${{ secrets.DOCKERHUB_USERNAME }} \
            --docker-password ${{ secrets.DOCKERHUB_TOKEN }}
      - name: 🚀 Dispatch Repository Updater update signal
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.DISPATCH_TOKEN }}
          repository: ikifar2012/ha-addons
          event-type: update
          client-payload: '{"addon": "amcrest2mqtt-addon"}'